export interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  remote: "Remote" | "Hybrid" | "On-site";
  type: "Full-time" | "Part-time" | "Contract";
  niche: "AI/ML" | "Healthcare IT" | "FinTech" | "Cybersecurity";
  experienceLevel: "Entry" | "Mid" | "Senior" | "Lead";
  salary: {
    min: number;
    max: number;
  };
  tags: string[];
  description: string;
  posted: string;
  logo: string;
}

export const mockJobs: Job[] = [
  {
    id: 1,
    title: "Senior Machine Learning Engineer",
    company: "TechCorp AI",
    location: "San Francisco, CA",
    remote: "Hybrid",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Senior",
    salary: { min: 150000, max: 220000 },
    tags: ["Python", "TensorFlow", "PyTorch", "MLOps"],
    description: "Lead ML initiatives and build scalable AI systems.",
    posted: "2 days ago",
    logo: "🚀",
  },
  {
    id: 2,
    title: "AI Research Scientist",
    company: "DeepMind Labs",
    location: "New York, NY",
    remote: "Remote",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Senior",
    salary: { min: 180000, max: 250000 },
    tags: ["Research", "Deep Learning", "NLP", "Computer Vision"],
    description: "Conduct cutting-edge research in deep learning and AI.",
    posted: "1 day ago",
    logo: "🧠",
  },
  {
    id: 3,
    title: "Healthcare Data Engineer",
    company: "MediTech Solutions",
    location: "Boston, MA",
    remote: "Hybrid",
    type: "Full-time",
    niche: "Healthcare IT",
    experienceLevel: "Mid",
    salary: { min: 110000, max: 150000 },
    tags: ["SQL", "ETL", "HIPAA", "Python"],
    description: "Build and maintain healthcare data pipelines.",
    posted: "3 days ago",
    logo: "🏥",
  },
  {
    id: 4,
    title: "Cybersecurity Analyst",
    company: "SecureNet Inc",
    location: "Washington, DC",
    remote: "On-site",
    type: "Full-time",
    niche: "Cybersecurity",
    experienceLevel: "Mid",
    salary: { min: 95000, max: 135000 },
    tags: ["Security", "Penetration Testing", "SIEM", "Incident Response"],
    description: "Monitor and respond to security threats and incidents.",
    posted: "5 days ago",
    logo: "🔒",
  },
  {
    id: 5,
    title: "FinTech Backend Developer",
    company: "PayFlow Systems",
    location: "Austin, TX",
    remote: "Remote",
    type: "Full-time",
    niche: "FinTech",
    experienceLevel: "Senior",
    salary: { min: 140000, max: 190000 },
    tags: ["Java", "Microservices", "Payment Systems", "AWS"],
    description: "Develop secure and scalable payment processing systems.",
    posted: "1 week ago",
    logo: "💳",
  },
  {
    id: 6,
    title: "Junior Data Scientist",
    company: "Analytics Pro",
    location: "Chicago, IL",
    remote: "Hybrid",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Entry",
    salary: { min: 75000, max: 95000 },
    tags: ["Python", "Statistics", "SQL", "Tableau"],
    description: "Analyze data and build predictive models.",
    posted: "4 days ago",
    logo: "📊",
  },
  {
    id: 7,
    title: "MLOps Engineer",
    company: "CloudScale",
    location: "Seattle, WA",
    remote: "Remote",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Mid",
    salary: { min: 130000, max: 170000 },
    tags: ["Kubernetes", "Docker", "CI/CD", "AWS", "MLflow"],
    description: "Deploy and maintain ML models in production.",
    posted: "2 days ago",
    logo: "☁️",
  },
  {
    id: 8,
    title: "Healthcare Software Architect",
    company: "HealthSync",
    location: "Denver, CO",
    remote: "Hybrid",
    type: "Full-time",
    niche: "Healthcare IT",
    experienceLevel: "Lead",
    salary: { min: 160000, max: 210000 },
    tags: ["Architecture", "HL7", "FHIR", "Microservices"],
    description: "Design healthcare software architecture and systems.",
    posted: "1 week ago",
    logo: "🏥",
  },
  {
    id: 9,
    title: "Security Operations Engineer",
    company: "CyberGuard",
    location: "Remote",
    remote: "Remote",
    type: "Full-time",
    niche: "Cybersecurity",
    experienceLevel: "Senior",
    salary: { min: 125000, max: 165000 },
    tags: ["SOC", "Threat Hunting", "SIEM", "Splunk"],
    description: "Operate security systems and respond to threats.",
    posted: "3 days ago",
    logo: "🛡️",
  },
  {
    id: 10,
    title: "Blockchain Developer",
    company: "CryptoFinance",
    location: "Miami, FL",
    remote: "Remote",
    type: "Contract",
    niche: "FinTech",
    experienceLevel: "Mid",
    salary: { min: 120000, max: 160000 },
    tags: ["Solidity", "Ethereum", "Smart Contracts", "Web3"],
    description: "Develop blockchain solutions for financial applications.",
    posted: "6 days ago",
    logo: "⛓️",
  },
  {
    id: 11,
    title: "Computer Vision Engineer",
    company: "VisionTech",
    location: "Boston, MA",
    remote: "Hybrid",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Senior",
    salary: { min: 135000, max: 185000 },
    tags: ["OpenCV", "YOLO", "CNN", "PyTorch"],
    description: "Build computer vision systems for real-world applications.",
    posted: "4 days ago",
    logo: "👁️",
  },
  {
    id: 12,
    title: "EHR Integration Specialist",
    company: "HealthBridge",
    location: "Phoenix, AZ",
    remote: "On-site",
    type: "Full-time",
    niche: "Healthcare IT",
    experienceLevel: "Mid",
    salary: { min: 90000, max: 120000 },
    tags: ["HL7", "FHIR", "Epic", "Cerner"],
    description: "Integrate electronic health record systems.",
    posted: "5 days ago",
    logo: "🔗",
  },
  {
    id: 13,
    title: "Penetration Tester",
    company: "RedTeam Security",
    location: "San Diego, CA",
    remote: "Hybrid",
    type: "Full-time",
    niche: "Cybersecurity",
    experienceLevel: "Mid",
    salary: { min: 100000, max: 140000 },
    tags: ["Ethical Hacking", "Metasploit", "Burp Suite", "OSCP"],
    description: "Conduct security assessments and penetration tests.",
    posted: "1 week ago",
    logo: "🎯",
  },
  {
    id: 14,
    title: "Quantitative Developer",
    company: "HedgeFund Alpha",
    location: "New York, NY",
    remote: "On-site",
    type: "Full-time",
    niche: "FinTech",
    experienceLevel: "Senior",
    salary: { min: 180000, max: 280000 },
    tags: ["C++", "Python", "Algorithms", "Trading Systems"],
    description: "Develop high-frequency trading algorithms.",
    posted: "2 days ago",
    logo: "📈",
  },
  {
    id: 15,
    title: "NLP Engineer",
    company: "LangTech AI",
    location: "Remote",
    remote: "Remote",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Mid",
    salary: { min: 125000, max: 165000 },
    tags: ["NLP", "Transformers", "BERT", "SpaCy"],
    description: "Build natural language processing systems.",
    posted: "3 days ago",
    logo: "💬",
  },
  {
    id: 16,
    title: "Healthcare DevOps Engineer",
    company: "MedCloud",
    location: "Portland, OR",
    remote: "Remote",
    type: "Full-time",
    niche: "Healthcare IT",
    experienceLevel: "Senior",
    salary: { min: 130000, max: 170000 },
    tags: ["AWS", "Terraform", "Docker", "Kubernetes"],
    description: "Manage healthcare cloud infrastructure.",
    posted: "1 week ago",
    logo: "⚙️",
  },
  {
    id: 17,
    title: "Cloud Security Architect",
    company: "SecureCloud",
    location: "Dallas, TX",
    remote: "Hybrid",
    type: "Full-time",
    niche: "Cybersecurity",
    experienceLevel: "Lead",
    salary: { min: 155000, max: 205000 },
    tags: ["AWS Security", "Azure", "Zero Trust", "IAM"],
    description: "Design secure cloud architectures and policies.",
    posted: "4 days ago",
    logo: "🔐",
  },
  {
    id: 18,
    title: "Payment Gateway Engineer",
    company: "PaymentHub",
    location: "Los Angeles, CA",
    remote: "Hybrid",
    type: "Full-time",
    niche: "FinTech",
    experienceLevel: "Mid",
    salary: { min: 115000, max: 155000 },
    tags: ["API", "Payment Processing", "Security", "Node.js"],
    description: "Build and maintain payment gateway systems.",
    posted: "5 days ago",
    logo: "💰",
  },
  {
    id: 19,
    title: "AI Product Manager",
    company: "AI Ventures",
    location: "San Francisco, CA",
    remote: "Remote",
    type: "Full-time",
    niche: "AI/ML",
    experienceLevel: "Senior",
    salary: { min: 145000, max: 195000 },
    tags: ["Product Management", "AI Strategy", "Roadmap", "Agile"],
    description: "Lead AI product development and strategy.",
    posted: "2 days ago",
    logo: "🎯",
  },
  {
    id: 20,
    title: "Medical Imaging AI Engineer",
    company: "RadAI",
    location: "Baltimore, MD",
    remote: "Hybrid",
    type: "Full-time",
    niche: "Healthcare IT",
    experienceLevel: "Senior",
    salary: { min: 140000, max: 180000 },
    tags: ["Medical Imaging", "Deep Learning", "DICOM", "Python"],
    description: "Develop AI solutions for medical image analysis.",
    posted: "6 days ago",
    logo: "🔬",
  },
];
